[package]
name = "wassup"
version = "0.1.0"
authors = ["Julius Rakow <julius@rakow.me>"]
edition = "2018"

[[bin]]
name = "wassup"
path = "src/main.rs"

[dependencies]
parity-wasm = "0.37.0"
wassup-z3 = { path = "../wassup-z3" }
