[workspace]
members = ["cli"]

[package]
name = "wassup"
version = "0.1.0"
authors = ["Julius Rakow <julius@rakow.me>"]
edition = "2018"

[dependencies]
parity-wasm = "0.37.0"
z3 = { path = "../z3.rs/z3" }

[dev-dependencies]
wabt = "0.7.4"
